"""
Automated Customer Onboarding Checklist Generator
Reads a customer config JSON and generates a tailored HTML onboarding checklist.
Replaces the manual copy-and-edit process for each new enterprise customer.
"""

import json
import os
from datetime import datetime
from jinja2 import Template


TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Onboarding Checklist – {{ customer.name }}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f7fa; color: #1a1a1a; padding: 40px 20px; }
    .container { max-width: 760px; margin: 0 auto; }
    header { background: #1A3C6E; color: white; padding: 32px; border-radius: 8px 8px 0 0; }
    header h1 { font-size: 22px; font-weight: 600; }
    header p { font-size: 13px; opacity: 0.75; margin-top: 6px; }
    .meta { background: white; padding: 16px 32px; border-bottom: 1px solid #e5e7eb; display: flex; gap: 32px; }
    .meta span { font-size: 13px; color: #666; }
    .meta strong { color: #1a1a1a; }
    .section { background: white; border-bottom: 1px solid #e5e7eb; }
    .section-title { padding: 18px 32px 12px; font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: #1A3C6E; }
    .item { display: flex; align-items: flex-start; gap: 14px; padding: 12px 32px; border-top: 1px solid #f0f0f0; }
    .checkbox { width: 18px; height: 18px; border: 2px solid #ccc; border-radius: 4px; flex-shrink: 0; margin-top: 2px; }
    .item-text { flex: 1; }
    .item-title { font-size: 14px; font-weight: 500; }
    .item-desc { font-size: 12px; color: #888; margin-top: 3px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 99px; font-size: 11px; font-weight: 600; margin-left: 8px; vertical-align: middle; }
    .badge-required { background: #fef3c7; color: #92400e; }
    .badge-optional { background: #f0fdf4; color: #166534; }
    footer { background: white; border-radius: 0 0 8px 8px; padding: 16px 32px; font-size: 12px; color: #aaa; border-top: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Onboarding Checklist</h1>
      <p>{{ customer.name }} &nbsp;·&nbsp; {{ customer.plan | upper }} Plan &nbsp;·&nbsp; Generated {{ generated_at }}</p>
    </header>

    <div class="meta">
      <span><strong>Account Owner:</strong> {{ customer.account_owner }}</span>
      <span><strong>Target Go-Live:</strong> {{ customer.go_live_date }}</span>
      <span><strong>Integrations:</strong> {{ customer.integrations | join(', ') }}</span>
    </div>

    {% for section in sections %}
    <div class="section">
      <div class="section-title">{{ section.title }}</div>
      {% for item in section.items %}
      <div class="item">
        <div class="checkbox"></div>
        <div class="item-text">
          <div class="item-title">
            {{ item.title }}
            <span class="badge badge-{{ 'required' if item.required else 'optional' }}">
              {{ 'Required' if item.required else 'Optional' }}
            </span>
          </div>
          {% if item.description %}
          <div class="item-desc">{{ item.description }}</div>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
    {% endfor %}

    <footer>Generated by Onboarding Checklist Generator &nbsp;·&nbsp; Do not share externally without review.</footer>
  </div>
</body>
</html>
"""


def build_sections(customer: dict) -> list:
    """Build checklist sections based on customer plan and integrations."""
    plan = customer.get("plan", "starter").lower()
    integrations = [i.lower() for i in customer.get("integrations", [])]

    sections = []

    # Always included
    sections.append({
        "title": "Account Setup",
        "items": [
            {"title": "Confirm admin user credentials and login access", "required": True, "description": "Ensure the primary admin account is active and the customer can log in."},
            {"title": "Set up team members and assign roles", "required": True, "description": "Invite all relevant users and configure permissions based on their role."},
            {"title": "Configure notification preferences", "required": False, "description": "Set up email and in-app notification settings per user."},
        ]
    })

    # API section for plans that include it
    if plan in ("professional", "enterprise"):
        sections.append({
            "title": "API Configuration",
            "items": [
                {"title": "Generate and secure API credentials", "required": True, "description": "Create API keys and store them securely. Do not expose them in client-side code."},
                {"title": "Validate authentication against sandbox environment", "required": True, "description": "Confirm API key auth is working before moving to production."},
                {"title": "Review rate limits and pagination behaviour", "required": True, "description": "Ensure the integration handles paginated responses and respects rate limit headers."},
                {"title": "Test error handling for 4xx and 5xx responses", "required": False, "description": "Confirm the integration handles error responses gracefully."},
            ]
        })

    # Integration-specific sections
    if "zapier" in integrations:
        sections.append({
            "title": "Zapier Integration",
            "items": [
                {"title": "Connect Zapier account and authenticate", "required": True, "description": None},
                {"title": "Configure trigger events and test with sample data", "required": True, "description": None},
                {"title": "Enable and monitor live Zaps", "required": False, "description": None},
            ]
        })

    if "salesforce" in integrations or "crm" in integrations:
        sections.append({
            "title": "CRM Integration",
            "items": [
                {"title": "Map CRM fields to platform objects", "required": True, "description": "Ensure lead, contact, and account fields are correctly mapped."},
                {"title": "Configure sync direction and frequency", "required": True, "description": "Decide if sync is one-way or bidirectional and set the schedule."},
                {"title": "Test sync with a sample record", "required": True, "description": None},
                {"title": "Verify deduplication rules are active", "required": False, "description": None},
            ]
        })

    if "slack" in integrations:
        sections.append({
            "title": "Slack Integration",
            "items": [
                {"title": "Install the app in the customer's Slack workspace", "required": True, "description": None},
                {"title": "Configure alert channels for key event types", "required": True, "description": None},
            ]
        })

    # Enterprise-only
    if plan == "enterprise":
        sections.append({
            "title": "Enterprise Configuration",
            "items": [
                {"title": "Configure SSO / SAML authentication", "required": True, "description": "Set up identity provider connection and test login."},
                {"title": "Define custom data retention policies", "required": True, "description": None},
                {"title": "Review SLA terms and escalation contacts", "required": True, "description": None},
                {"title": "Schedule quarterly business review cadence", "required": False, "description": None},
            ]
        })

    # Always at the end
    sections.append({
        "title": "Go-Live Validation",
        "items": [
            {"title": "Run end-to-end smoke test in production", "required": True, "description": "Verify all configured features are working correctly in the live environment."},
            {"title": "Confirm customer sign-off on onboarding completion", "required": True, "description": None},
            {"title": "Schedule 30-day check-in call", "required": False, "description": None},
        ]
    })

    return sections


def generate_checklist(config_path: str, output_path: str = None):
    """Load a customer config JSON and generate an HTML checklist."""
    with open(config_path) as f:
        customer = json.load(f)

    sections = build_sections(customer)
    template = Template(TEMPLATE)
    html = template.render(
        customer=customer,
        sections=sections,
        generated_at=datetime.now().strftime("%d %B %Y")
    )

    if output_path is None:
        safe_name = customer["name"].replace(" ", "_").lower()
        output_path = f"checklist_{safe_name}.html"

    with open(output_path, "w") as f:
        f.write(html)

    print(f"Checklist generated: {output_path}")
    print(f"  Customer: {customer['name']}")
    print(f"  Plan:     {customer['plan']}")
    print(f"  Sections: {len(sections)}")
    return output_path


def _create_sample_config(path: str = "sample_customer.json") -> str:
    config = {
        "name": "Faulu Microfinance Bank",
        "plan": "enterprise",
        "account_owner": "Collins Ngumba",
        "go_live_date": "2024-04-01",
        "integrations": ["salesforce", "slack", "zapier"]
    }
    with open(path, "w") as f:
        json.dump(config, f, indent=2)
    return path


if __name__ == "__main__":
    import sys
    config_path = sys.argv[1] if len(sys.argv) > 1 else _create_sample_config()
    generate_checklist(config_path)
